# Curso de Python para não programadores
## Aula 03
Importar Arquivos CSV da internet com Pandas

In [1]:
import pandas as pd

In [11]:
# Copiar o link disponiblizado no portal dados abertos
url = 'http://repositorio.dados.gov.br/educacao/CADASTRO_MATRICULAS_REGIAO_NORTE_2012.csv'

df = pd.read_csv(url, encoding = 'cp1252', skiprows = 11, sep = ';')

df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ANO_CENSO,PK_COD_ENTIDADE,Nome_Escola,REDE,ID_DEPENDENCIA_ADM,Dependencia_Administrativa,CATESCPRIVADA,Localizacao,REGIAO,FK_COD_ESTADO,...,MATEEINCL,NESCEE,MATESPTOT,NESCEDESP,MATESP,NESCEDESPEXCLUS,MATESPEXCLUS,NESCEDESPCLESP,MATESPCLESP,ESCACESS
0,2012,11000023.0,EEEE PROFESSOR ABNAEL MACHADO DE LIMA - CENE,Pública,2.0,Estadual,NaN,Urbana,Norte,11.0,...,0.0,1.0,159.0,1.0,159.0,1.0,159.0,0.0,0.0,0.0
1,2012,11000040.0,EMEIEF PEQUENOS TALENTOS,Pública,3.0,Municipal,NaN,Urbana,Norte,11.0,...,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2012,11000058.0,CENTRO DE ENSINO CLASSE A,Privada,4.0,Privada,Particular,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2012,11000074.0,CENTRO DE ENSINO PLENO EXITO,Privada,4.0,Privada,NaN,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2012,11000082.0,CENTRO EDUCACIONAL PRESBITERIANO 15 DE NOVEMBRO,Privada,4.0,Privada,Particular,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
url = 'C:/Users/meu usuario/Documents/Curso Python/CADASTRO_MATRICULAS_REGIAO_NORTE_2012.csv'

df = pd.read_csv(url, encoding = 'cp1252', skiprows = 11, sep = ';')

df.head()

,ANO_CENSO,PK_COD_ENTIDADE,Nome_Escola,REDE,ID_DEPENDENCIA_ADM,Dependencia_Administrativa,CATESCPRIVADA,Localizacao,REGIAO,FK_COD_ESTADO,...,MATEEINCL,NESCEE,MATESPTOT,NESCEDESP,MATESP,NESCEDESPEXCLUS,MATESPEXCLUS,NESCEDESPCLESP,MATESPCLESP,ESCACESS
0,2012,11000023.0,EEEE PROFESSOR ABNAEL MACHADO DE LIMA - CENE,Pública,2.0,Estadual,NaN,Urbana,Norte,11.0,...,0.0,1.0,159.0,1.0,159.0,1.0,159.0,0.0,0.0,0.0
1,2012,11000040.0,EMEIEF PEQUENOS TALENTOS,Pública,3.0,Municipal,NaN,Urbana,Norte,11.0,...,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2012,11000058.0,CENTRO DE ENSINO CLASSE A,Privada,4.0,Privada,Particular,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2012,11000074.0,CENTRO DE ENSINO PLENO EXITO,Privada,4.0,Privada,NaN,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2012,11000082.0,CENTRO EDUCACIONAL PRESBITERIANO 15 DE NOVEMBRO,Privada,4.0,Privada,Particular,Urbana,Norte,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Obrigado!
## Acesse o blog www.catadados.com para mais informações.
## Abraços.